name: Deploy React App to S3
on: 
    push:
        branches: 
            - main

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    AWS_REGION: eu-north-1
    AWS_S3_BUCKET: citizenconnectapp

jobs:
    build-and-deploy: 
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4

        - name: Cache dependencies
          uses: actions/cache@v3
          with: 
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('Frontend/citizen-connect/package-lock.json')}}    
            restore-keys: |
                ${{ runner.os }}-node-  

        - name: Install dependencies
          run: |
            cd Frontend/citizen-connect
            npm install

        - name: Build React App
          run: |
            cd Frontend/citizen-connect
            npm run build

        - name: Debug directory structure (Optional)
          run: ls -R Frontend/citizen-connect/build

        - name: Configure AWS
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Deploy to S3
          run: |
            aws s3 sync Frontend/citizen-connect/build s3://$AWS_S3_BUCKET --delete \
            --cache-control "max-age=31536000"

            aws s3 cp Frontend/citizen-connect/build/index.html s3://$AWS_S3_BUCKET/index.html \
            --content-type "text/html" \
            --cache-control "no-cache, no-store, must-revalidate"
